import type { Metadata } from "next";
import flagsmith from "flagsmith/isomorphic";
import { FeatureFlagProvider } from "./components/FeatureFlagProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await flagsmith.init({
    environmentID: process.env.Flagsmith,
    identity: "test_user_id",
  });
  const serverState = flagsmith.getState();

  return (
    <html lang="en">
      <body>
        <FeatureFlagProvider serverState={serverState}>
          {children}
        </FeatureFlagProvider>
      </body>
    </html>
  );
}
