import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import Provider from "./growthbook-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const gb = new GrowthBook({
    apiHost: "https://cdn.growthbook.io",
    clientKey: "sdk-abc123",
    enableDevMode: true,
    trackingCallback: (experiment, result) => {
      console.log("Experiment Viewed", {
        experimentId: experiment.key,
        variationId: result.key,
      });
    },
  });
  gb.init({
    streaming: true,
  });

  return (
    <html lang="en">
      <body>
        <GrowthBookProvider growthbook={gb}>{children}</GrowthBookProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
